apiVersion: v1
kind: Service   
metadata:
  name: web-flask-svc
  labels:
    app: web-flask
spec:
  type: NodePort
  ports:
  - nodePort: 30036
    port: 3000   #servis portu
    targetPort: 5000  #container portu
  selector:
    app: web-flask
