apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw-deployment
  labels:
    app: cw
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cw
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: cw
    spec:
      containers:
      - name: cw
        image: nginx
        ports:
        - containerPort: 5000